# Generated by Django 3.0.5 on 2020-04-25 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_passport_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='passport_file',
            field=models.FileField(blank=True, null=True, upload_to='passports/'),
        ),
    ]
