# Generated by Django 3.0.5 on 2020-05-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_auto_20200425_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_file',
            field=models.FileField(blank=True, null=True, upload_to='offers/'),
        ),
    ]
