# Generated by Django 3.0.5 on 2020-07-01 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_settings'),
    ]

    operations = [
        migrations.RenameField(
            model_name='settings',
            old_name='rewriting',
            new_name='is_rewriting',
        ),
        migrations.AddField(
            model_name='settings',
            name='name',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
